export const Questions = [
    {
        prompt: 'What is 1+3?',
        optionA: "24",
        optionB: "21",
        optionC: "4",
        optionD: "2",
        answer: "C",
    },
    {
        prompt: 'Which is a streaminng platform?',
        optionA: "Amazon Prime",
        optionB: "WhatsApp",
        optionC: "Twitter",
        optionD: "Google",
        answer: "A",
    },
    {
        prompt: 'Which tech youtube channel focuses on CSS?',
        optionA: "Web Dev Simplified",
        optionB: "PedroTech",
        optionC: "NetNinja",
        optionD: "Kevin Powell",
        answer: "D",
    },
    {
        prompt: 'Which is the best mode in call of duty mobile?',
        optionA: "Multiplayer",
        optionB: "Zombie",
        optionC: "Training",
        optionD: "Battle Royale",
        answer: "D",
    },
    {
        prompt: 'Who wrote the famous book "Rich Dad Poor Dad"',
        optionA: "Robert Kiyosaki",
        optionB: "Juan Pedro",
        optionC: "Al Amin Hassan",
        optionD: "Robert Huerta",
        answer: "A",
    },
    {
        prompt: 'What does HTML stand for?',
        optionA: "Hyper Train",
        optionB: "PedroTech",
        optionC: "NetNinja",
        optionD: "Kevin Powell",
        answer: "D",
    },
]